# Generated by Django 5.2.8 on 2026-03-16 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_productcategory_whatsappcampaign_lead_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('messages', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIActivityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('sentiment_label', models.CharField(blank=True, max_length=20)),
                ('intent', models.CharField(blank=True, max_length=100)),
                ('urgency', models.CharField(blank=True, max_length=20)),
                ('key_topics', models.JSONField(blank=True, default=list)),
                ('buying_signals', models.JSONField(blank=True, default=list)),
                ('objections', models.JSONField(blank=True, default=list)),
                ('competitor_mentions', models.JSONField(blank=True, default=list)),
                ('one_line_summary', models.TextField(blank=True)),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('follow_up_suggestion', models.TextField(blank=True)),
                ('follow_up_days', models.IntegerField(default=3)),
                ('full_analysis', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='crm.activity')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_activity_analyses', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('churn_risk', 'Churn Risk'), ('engagement_spike', 'Engagement Spike'), ('score_change', 'Score Change'), ('competitor_mention', 'Competitor Mentioned'), ('ghost_lead', 'Ghost Lead'), ('stagnant_deal', 'Stagnant Deal'), ('follow_up_overdue', 'Follow-up Overdue'), ('high_value_alert', 'High Value Alert')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_actioned', models.BooleanField(default=False)),
                ('suggested_action', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_alerts', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('proposal', 'Business Proposal'), ('email_sequence', 'Email Sequence'), ('battle_card', 'Battle Card'), ('meeting_brief', 'Meeting Brief')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_documents', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AILeadProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('conversion_probability', models.FloatField(default=0.0)),
                ('priority_rank', models.IntegerField(default=5)),
                ('churn_risk', models.FloatField(default=0.0)),
                ('deal_risk_level', models.CharField(blank=True, default='unknown', max_length=20)),
                ('sentiment_trend', models.CharField(blank=True, max_length=20)),
                ('engagement_velocity', models.FloatField(default=0.0)),
                ('recommended_action', models.TextField(blank=True)),
                ('competitor_mentions', models.JSONField(blank=True, default=list)),
                ('suggested_tags', models.JSONField(blank=True, default=list)),
                ('best_contact_time', models.JSONField(blank=True, default=dict)),
                ('last_score_factors', models.JSONField(blank=True, default=dict)),
                ('last_ai_response', models.JSONField(blank=True, default=dict)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to='crm.lead')),
            ],
            options={
                'verbose_name': 'AI Lead Profile',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='AIScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('conversion_probability', models.FloatField(default=0.0)),
                ('churn_risk', models.FloatField(default=0.0)),
                ('factors', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_score_history', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
