# Generated by Django 5.2.8 on 2026-03-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_aichatsession_aiactivityanalysis_aialert_aidocument_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aileadprofile',
            options={'ordering': ['-score']},
        ),
        migrations.AlterField(
            model_name='aialert',
            name='alert_type',
            field=models.CharField(choices=[('churn_risk', 'Churn Risk'), ('engagement_spike', 'Engagement Spike'), ('score_change', 'Score Change'), ('competitor_mention', 'Competitor Mentioned'), ('ghost_lead', 'Ghost Lead'), ('stagnant_deal', 'Stagnant Deal'), ('follow_up_overdue', 'Follow-up Overdue')], max_length=30),
        ),
    ]
