# Generated by Django 5.2.8 on 2026-03-17 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_aileadprofile_options_alter_aialert_alert_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngagementTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BDMTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('target_type', models.CharField(choices=[('region', 'Region'), ('vertical', 'Vertical'), ('product', 'Product'), ('rep', 'Sales Rep'), ('campaign', 'Campaign')], max_length=50)),
                ('target_leads', models.IntegerField(default=0)),
                ('target_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('achieved_leads', models.IntegerField(default=0)),
                ('achieved_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='active', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.campaign')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.region')),
                ('vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.vertical')),
                ('product_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.productline')),
            ],
        ),
        migrations.CreateModel(
            name='BDMReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('summary', models.TextField()),
                ('findings', models.TextField(blank=True)),
                ('action_items', models.TextField(blank=True)),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='crm.bdmtarget')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('content_theme', models.CharField(blank=True, max_length=200)),
                ('target_description', models.TextField(blank=True)),
                ('selected_channel', models.CharField(default='whatsapp', max_length=50)),
                ('prompt_used', models.TextField(blank=True)),
                ('generated_subject', models.CharField(blank=True, max_length=255)),
                ('generated_content', models.TextField(blank=True)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.region')),
                ('selected_vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.vertical')),
                ('selected_product_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.productline')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('interested', 'Interested'), ('demo_requested', 'Demo Requested'), ('price_requested', 'Price Requested'), ('follow_up_later', 'Follow Up Later'), ('not_interested', 'Not Interested'), ('invalid_lead', 'Invalid Lead'), ('competitor', 'Competitor Mentioned'), ('no_response', 'No Response')], max_length=50)),
                ('response_text', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_responses', to='crm.lead')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='crm.campaignworkspace')),
            ],
        ),
        migrations.CreateModel(
            name='LeadBusinessMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifecycle_type', models.CharField(choices=[('target', 'Target Customer'), ('current', 'Current Customer'), ('repeat', 'Repeat Customer'), ('dormant', 'Dormant Customer')], default='target', max_length=50)),
                ('last_purchase_date', models.DateField(blank=True, null=True)),
                ('last_purchase_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase_frequency_days', models.IntegerField(default=0)),
                ('conversion_probability', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('customer_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customercategory')),
                ('engagement_tools', models.ManyToManyField(blank=True, related_name='lead_business_metas', to='crm.engagementtool')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_meta', to='crm.lead')),
                ('product_lines', models.ManyToManyField(blank=True, related_name='lead_business_metas', to='crm.productline')),
                ('sales_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.saleschannel')),
            ],
        ),
    ]
