# Generated by Django 5.2.8 on 2026-03-19 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_customercategory_engagementtool_productline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('decision_maker', 'Decision Maker'), ('influencer', 'Influencer'), ('gatekeeper', 'Gatekeeper'), ('user', 'End User')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_contacts', to='crm.lead')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('brochure', 'Company Profile/Brochure'), ('demo', 'Product Demo Video'), ('price_list', 'Price List'), ('image', 'Creative Image')], max_length=20)),
                ('file', models.FileField(upload_to='marketing_assets/')),
                ('whatsapp_media_id', models.CharField(blank=True, help_text='ID for fast sending via WhatsApp API', max_length=100)),
                ('associated_vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.vertical')),
            ],
        ),
    ]
