# Generated by Django 5.2.8 on 2026-03-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_keycontact_marketingasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
