# Generated by Django 5.2.8 on 2026-03-31 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdmtarget',
            name='customer_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customercategory'),
        ),
        migrations.AddField(
            model_name='bdmtarget',
            name='engagement_tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.engagementtool'),
        ),
        migrations.AddField(
            model_name='bdmtarget',
            name='sales_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.saleschannel'),
        ),
        migrations.AlterField(
            model_name='bdmtarget',
            name='target_type',
            field=models.CharField(choices=[('region', 'Region'), ('vertical', 'Vertical'), ('product', 'Product'), ('customer_category', 'Customer Category'), ('sales_channel', 'Sales Channel'), ('engagement_tool', 'Engagement Tool')], max_length=50),
        ),
    ]
