# Generated by Django 5.2.8 on 2026-05-07 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_bdmtarget_customer_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('role_mode', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='admin', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activity_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlannerMemberPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=150)),
                ('workspace_name', models.CharField(max_length=200)),
                ('monthly_calls_target', models.PositiveIntegerField(default=0)),
                ('monthly_whatsapp_target', models.PositiveIntegerField(default=0)),
                ('monthly_email_target', models.PositiveIntegerField(default=0)),
                ('monthly_linkedin_target', models.PositiveIntegerField(default=0)),
                ('calls_weightage', models.PositiveSmallIntegerField(default=25)),
                ('whatsapp_weightage', models.PositiveSmallIntegerField(default=25)),
                ('email_weightage', models.PositiveSmallIntegerField(default=25)),
                ('linkedin_weightage', models.PositiveSmallIntegerField(default=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_activity_member_plans', to=settings.AUTH_USER_MODEL)),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_plans', to='crm.activityplanner')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_member_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['member_name'],
            },
        ),
        migrations.CreateModel(
            name='PlannerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('daily', 'Daily')], max_length=20)),
                ('week_number', models.PositiveSmallIntegerField(default=1)),
                ('task_date', models.DateField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('calls', 'Calls'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('target_count', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done')], default='pending', max_length=20)),
                ('created_by_admin', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.plannermemberplan')),
            ],
            options={
                'ordering': ['week_number', 'task_date', 'channel'],
            },
        ),
    ]
