# Generated by Django 5.2.8 on 2026-06-01 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_contact_delete_keycontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': False},
        ),
    ]
