from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0013_alter_contact_options"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS contacts (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    region varchar(100) NULL,
                    location varchar(100) NOT NULL DEFAULT '',
                    vertical varchar(100) NULL,
                    company_name varchar(255) NOT NULL DEFAULT '',
                    person_name varchar(255) NULL,
                    designation varchar(255) NULL,
                    email varchar(254) NULL,
                    phone varchar(50) NULL,
                    address text NULL,
                    is_verified boolean NOT NULL DEFAULT false,
                    created_at timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone NOT NULL
                );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"db_table": "contacts"},
        ),
    ]

