# Generated by Django 5.2.8 on 2026-07-09 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_accounttargetcompany_accounttargetpic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerCallAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField(default=1)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_call_assignments', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_call_assignments', to='crm.contact')),
                ('member_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_assignments', to='crm.plannermemberplan')),
                ('planner_task', models.ForeignKey(limit_choices_to={'channel': 'calls', 'period_type': 'daily'}, on_delete=django.db.models.deletion.CASCADE, related_name='call_assignments', to='crm.plannertask')),
            ],
            options={
                'ordering': ['scheduled_date', 'sequence_number', 'id'],
                'constraints': [models.UniqueConstraint(fields=('planner_task', 'contact'), name='uniq_planner_task_contact_assignment'), models.UniqueConstraint(fields=('member_plan', 'contact'), name='uniq_member_plan_contact_assignment')],
            },
        ),
    ]
