# Generated by Django 5.2.8 on 2026-07-21 12:06

import crm.tenancy
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_activityplanner_source_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttargetcompany',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='accounttargetpic',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='activityplanner',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='aiactivityanalysis',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='aialert',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='aidocument',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='aiinteractionlog',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='aileadprofile',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='aiscoresnapshot',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='bdmreview',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='bdmtarget',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='campaignresponse',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='campaignworkspace',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='company',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='consumptionpattern',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='course',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='customercategory',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='engagementtool',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='industry',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='leadbusinessmeta',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='marketingasset',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='module',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='plannercallassignment',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='plannermemberplan',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='plannertask',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='productline',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='region',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='task',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='vertical',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='whatsappcampaign',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='wishlistentry',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
        migrations.AlterField(
            model_name='accounttargetcompany',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accounttargetcompany',
            name='normalized_name',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='aichatsession',
            name='session_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customercategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='engagementtool',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productline',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='saleschannel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='accounttargetcompany',
            constraint=models.UniqueConstraint(fields=('tenant_company_id', 'normalized_name'), name='uniq_target_company_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='aichatsession',
            constraint=models.UniqueConstraint(fields=('tenant_company_id', 'session_id'), name='uniq_ai_session_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='customercategory',
            constraint=models.UniqueConstraint(fields=('tenant_company_id', 'name'), name='uniq_customer_category_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='engagementtool',
            constraint=models.UniqueConstraint(fields=('tenant_company_id', 'name'), name='uniq_engagement_tool_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='productline',
            constraint=models.UniqueConstraint(fields=('tenant_company_id', 'name'), name='uniq_product_line_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='saleschannel',
            constraint=models.UniqueConstraint(fields=('tenant_company_id', 'name'), name='uniq_sales_channel_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('tenant_company_id', 'name'), name='uniq_tag_per_tenant'),
        ),
    ]
