# Generated by Django 5.2.8 on 2026-07-21 12:12

import crm.tenancy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_accounttargetcompany_tenant_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_column='tenant_id', db_index=True, default=crm.tenancy.get_current_company_id, editable=False),
        ),
    ]
