# Generated by Django 4.2 on 2026-08-17 05:44

import crm.tenancy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_contact_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttargetcompany',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='accounttargetpic',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='activityplanner',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='aiactivityanalysis',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='aialert',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='aidocument',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='aiinteractionlog',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='aileadprofile',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='aiscoresnapshot',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='bdmreview',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='bdmtarget',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='campaignresponse',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='campaignworkspace',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='company',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='consumptionpattern',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='course',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='customercategory',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='engagementtool',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='industry',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='leadbusinessmeta',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='marketingasset',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='module',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='plannercallassignment',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='plannermemberplan',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='plannertask',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='productline',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='region',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='task',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='vertical',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='whatsappcampaign',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
        migrations.AddField(
            model_name='wishlistentry',
            name='tenant_company_id',
            field=models.PositiveBigIntegerField(db_index=True, default=crm.tenancy.current_company_id, editable=False),
        ),
    ]
