# Generated by Django 5.2.8 on 2026-08-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_tenant_isolation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tenant_company_id',
        ),
    ]
